name: elminiawy
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  #A build system for Dart code generation and modular compilation
  # dart run build_runner build --delete-conflicting-outputs
  build_runner: ^2.4.7
  # State management
  flutter_bloc: ^8.1.3
  # Code generator (mainly used with cubit & retrofit)
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  # for dependency injection
  get_it: ^8.0.0
  # Automatically generate code for converting to and from JSON by annotating Dart classes
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  # Networking
  dio: ^5.3.3
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.4
  pretty_dio_logger: ^1.3.1
  # localization
  intl: ^0.19.0
  easy_localization: ^3.0.3
  # An SVG rendering and widget library for Flutter, which allows painting
  flutter_svg: ^2.0.10+1
  # for adapting screen and font size.
  flutter_screenutil: ^5.9.0
  firebase_core: ^3.6.0
  # Flutter library to load and cache network images.
  cached_network_image: ^3.3.1
  # reading and writing simple key-value pairs
  shared_preferences: ^2.2.3
  # provides API to store data in secure storage.
  flutter_secure_storage: ^9.2.2
  # easy way to add shimmer effect
  shimmer: ^3.0.0
  #show toast message
  toastification: ^2.0.0
  # internet_connection_checker
  internet_connection_checker: 1.0.0+1
  # animation
  animate_do: ^3.3.4
  # splash screen
  flutter_native_splash: ^2.4.1
  # icon
  flutter_iconly: ^1.0.2
  # country code
  country_code_picker: ^3.0.0
  flutter_verification_code: ^1.1.7
  iconly: ^1.0.1
  navigation_view: ^1.0.6
  persistent_bottom_nav_bar_v2: ^5.3.0
  fan_carousel_image_slider: ^1.0.1
  carousel_slider: ^5.0.0
  device_preview: ^1.2.0
  modal_bottom_sheet: ^3.0.0
  flutter_slidable: ^3.1.1
  flutter_rating_bar: ^4.0.1
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  flutter_google_maps_webservices: ^1.1.1
  geocoding: ^3.0.0
  http: ^1.2.2
  widget_to_marker: ^1.0.6
  custom_map_markers: ^0.0.2+1
  coupon_uikit: ^0.2.1
  lottie: ^3.1.2
  skeletonizer: ^1.4.2
  flutter_local_notifications: ^17.2.2
  firebase_messaging: ^15.1.2
  badges: ^3.1.2
  flutter_dotenv: ^5.1.0
  connectivity_plus: ^6.0.5
  rxdart: ^0.28.0
  flutter_localizations:
    sdk: flutter
  dart_ping: ^9.0.1
  google_sign_in: ^6.2.1
  firebase_auth: ^5.3.1
  smooth_page_indicator: ^1.2.0+3


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - lang/ar.json
    - lang/en.json
    - asset/image/
    - asset/json/



    


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Acme
      fonts:
        - asset: asset/fonts/Acme-Regular.ttf


    - family: Cairo
      fonts:
        - asset: asset/fonts/Cairo-Black.ttf
          weight: 900

        - asset: asset/fonts/Cairo-Bold.ttf
          weight: 700

        - asset: asset/fonts/Cairo-ExtraBold.ttf
          weight: 800

        - asset: asset/fonts/Cairo-ExtraLight.ttf
          weight: 200

        - asset: asset/fonts/Cairo-Light.ttf
          weight: 300

        - asset: asset/fonts/Cairo-Medium.ttf
          weight: 500

        - asset: asset/fonts/Cairo-Regular.ttf
          weight: 400

        - asset: asset/fonts/Cairo-SemiBold.ttf
          weight: 600    

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
